import type { FieldGroup } from './types'
import { num, bool, sel, off, EP, ROUTE_MODES } from './helpers'

/** 外部池路由策略：唯一编辑入口在外部池页 → 策略 */
export const POOL_POLICY_GROUPS: FieldGroup[] = [
  {
    id: 'switch',
    title: '启用与直连',
    fields: [
      bool(`${EP}externalPoolsEnabled`, '启用外部池', '允许请求在本地不可调度或策略命中时进入外部池。'),
      bool(`${EP}externalDirectPolicyEnabled`, '外部直连策略', '命中直连模型或路径规则的请求直接走外部池。', {
        disabledWhen: off(`${EP}externalPoolsEnabled`),
      }),
      {
        kind: 'list',
        path: `${EP}directExternalModelRules`,
        label: '直连模型规则',
        desc: '每行一个模型名或通配',
        disabledWhen: (g) => !g(`${EP}externalPoolsEnabled`) || !g(`${EP}externalDirectPolicyEnabled`),
      },
      {
        kind: 'list',
        path: `${EP}directExternalPathRules`,
        label: '直连路径规则',
        desc: '每行一个路径前缀',
        disabledWhen: (g) => !g(`${EP}externalPoolsEnabled`) || !g(`${EP}externalDirectPolicyEnabled`),
      },
      bool(`${EP}directExternalOnLocalMaintenance`, '本地维护时直连', '本地保护熔断打开时请求直接走外部池。', { advanced: true }),
    ],
  },
  {
    id: 'routing',
    title: '入口路由',
    fields: [
      sel(`${EP}localPoolRouteMode`, '本地账号路由', '决定哪些入口允许进入本地账号。', ROUTE_MODES),
      {
        kind: 'list',
        path: `${EP}localPoolRouteRules`,
        label: '本地路由规则',
        desc: '每行一个路径前缀',
        disabledWhen: (g) => g(`${EP}localPoolRouteMode`) === 'allow_all',
      },
      sel(`${EP}externalPoolRouteMode`, '外部池路由', '决定哪些入口允许进入外部池。', ROUTE_MODES),
      {
        kind: 'list',
        path: `${EP}externalPoolRouteRules`,
        label: '外部池路由规则',
        desc: '每行一个路径前缀',
        disabledWhen: (g) => g(`${EP}externalPoolRouteMode`) === 'allow_all',
      },
    ],
  },
  {
    id: 'fallback',
    title: '何时兜底到外部池',
    fields: [
      bool(`${EP}localPoolPreflightEnabled`, '本地不可调度时预检外部池', '本地容量不足、无可用账号或调度 Redis 退化时优先尝试外部池。'),
      bool(`${EP}fallbackOnLocalCapacityExhausted`, '本地容量不足'),
      bool(`${EP}fallbackOnNoAvailableCredentials`, '没有可用账号'),
      bool(`${EP}fallbackOnLocalTransientExhausted`, '本地临时错误过多'),
      bool(`${EP}fallbackOnUnsupportedModel`, '本地不支持该模型'),
      bool(`${EP}fallbackOnSchedulerRedisDegraded`, '调度 Redis 降级'),
    ],
  },
  {
    id: 'circuit',
    title: '本地保护熔断',
    fields: [
      bool(`${EP}localPoolCircuitEnabled`, '启用本地保护统计', '短时间内多个账号连续失败时暂停本地调度。'),
      num(`${EP}localPoolCircuitWindowSecs`, '统计窗口', '', { min: 1, suffix: '秒', disabledWhen: off(`${EP}localPoolCircuitEnabled`) }),
      num(`${EP}localPoolCircuitOpenAfterFailures`, '失败阈值', '', {
        min: 1,
        suffix: '次',
        disabledWhen: off(`${EP}localPoolCircuitEnabled`),
      }),
      num(`${EP}localPoolCircuitRequireDistinctCredentials`, '至少涉及账号数', '', {
        min: 0,
        suffix: '个',
        disabledWhen: off(`${EP}localPoolCircuitEnabled`),
      }),
      num(`${EP}localPoolCircuitOpenSecs`, '暂停时长', '', { min: 1, suffix: '秒', disabledWhen: off(`${EP}localPoolCircuitEnabled`) }),
    ],
  },
  {
    id: 'rescue',
    title: '外部池失败后回本地',
    fields: [
      bool(`${EP}externalPoolLocalRescueEnabled`, '启用本地救援', '外部池作为兜底失败后，最后再尝试一次本地账号。'),
      bool(`${EP}externalPoolLocalRescueOnRateLimit`, '429 时回本地', '', { disabledWhen: off(`${EP}externalPoolLocalRescueEnabled`) }),
      bool(`${EP}externalPoolLocalRescueOnTimeout`, '超时时回本地', '', { disabledWhen: off(`${EP}externalPoolLocalRescueEnabled`) }),
      bool(`${EP}externalPoolLocalRescueOnCapacity`, '容量不足时回本地', '', { disabledWhen: off(`${EP}externalPoolLocalRescueEnabled`) }),
      num(`${EP}externalPoolLocalRescueMaxWaitSecs`, '最多等待本地空闲', '', {
        min: 0,
        max: 300,
        suffix: '秒',
        disabledWhen: off(`${EP}externalPoolLocalRescueEnabled`),
      }),
    ],
  },
  {
    id: 'capacity',
    title: '容量与重试',
    fields: [
      sel(`${EP}externalPoolCapacityMode`, '满并发处理', '', [
        ['fail_fast', '立即失败'],
        ['wait', '排队等待'],
      ]),
      num(`${EP}externalPoolGlobalMaxConcurrentRequests`, '全局最大并发', '所有外部池合计；0 表示不限制。', {
        min: 0,
        max: 100_000,
        suffix: '并发',
      }),
      num(`${EP}externalPoolMaxQueuedRequests`, '最大排队请求', '0 表示不排队。', { min: 0, max: 100_000, suffix: '请求' }),
      num(`${EP}externalPoolDispatchMaxWaitSecs`, '最长排队等待', '', { min: 1, max: 86_400, suffix: '秒' }),
      num(`${EP}externalPoolRetryMaxAttempts`, '跨池最多故障转移', '0 表示不重试其它外部池。', { min: 0, max: 10_000, suffix: '次' }),
      { kind: 'codes', path: `${EP}externalPoolRetryStatusCodes`, label: '跨池重试状态码', desc: '逗号分隔，例如 429, 500, 502' },
      bool(`${EP}externalPoolRetryOnNetworkError`, '网络错误跨池重试'),
      bool(`${EP}externalPoolRetryOnProtocolError`, '协议错误跨池重试'),
      num(`${EP}externalPoolSamePoolRetryCount`, '同池重试次数', '命中同池状态码时先在同一池重试。', { min: 0, max: 10, suffix: '次' }),
      {
        kind: 'codes',
        path: `${EP}externalPoolSamePoolRetryStatusCodes`,
        label: '同池重试状态码',
        disabledWhen: (g) => !g(`${EP}externalPoolSamePoolRetryCount`),
      },
      num(`${EP}externalPoolSamePoolRetryDelayMs`, '同池重试间隔', '', {
        min: 0,
        max: 60_000,
        suffix: '毫秒',
        disabledWhen: (g) => !g(`${EP}externalPoolSamePoolRetryCount`),
      }),
      num(`${EP}externalPoolTransientFailurePriorityPenalty`, '失败池临时降权', '瞬态失败后在窗口内临时增加有效优先级；0 表示关闭。', {
        min: 0,
        max: 10_000,
        suffix: '优先级',
        advanced: true,
      }),
      num(`${EP}externalPoolTransientFailureCooldownThreshold`, '连续失败计数（兼容）', '保留旧字段，不再触发池级冷却。', {
        min: 0,
        max: 1000,
        suffix: '次',
        advanced: true,
      }),
      num(`${EP}externalPoolMaxInputTokens`, '估算输入上限（兼容）', '保留历史配置，当前不用于拒绝。', {
        min: 0,
        suffix: 'tokens',
        advanced: true,
      }),
    ],
  },
  {
    id: 'timeout',
    title: '冷却与超时',
    fields: [
      num(`${EP}externalPoolRateLimitCooldownSecs`, '429 冷却', '', { min: 1, suffix: '秒' }),
      num(`${EP}externalPoolServerErrorCooldownSecs`, '5xx 冷却', '', { min: 1, suffix: '秒' }),
      num(`${EP}externalPoolNetworkErrorCooldownSecs`, '网络错误冷却', '', { min: 1, suffix: '秒' }),
      num(`${EP}externalPoolProtocolErrorCooldownSecs`, '协议/认证冷却', '', { min: 1, suffix: '秒' }),
      sel(`${EP}externalPoolModelUnavailableCooldownMode`, '模型不可用冷却范围', '', [
        ['disabled', '不冷却'],
        ['model', '仅该模型'],
        ['pool', '整个池'],
      ]),
      num(`${EP}externalPoolModelUnavailableCooldownSecs`, '模型不可用冷却', '', {
        min: 1,
        suffix: '秒',
        disabledWhen: (g) => g(`${EP}externalPoolModelUnavailableCooldownMode`) === 'disabled',
      }),
      num(`${EP}externalPoolRequestTimeoutSecs`, '非流式总超时', '', { min: 0, suffix: '秒' }),
      num(`${EP}externalPoolStreamRequestTimeoutSecs`, '流式总超时', '', { min: 0, suffix: '秒' }),
      num(`${EP}externalPoolStreamIdleTimeoutSecs`, '流式空闲超时', '', { min: 0, suffix: '秒' }),
      bool(`${EP}externalPoolStreamPreOutputRetryEnabled`, '流式首输出前错误换池', '未提交内容前遇到错误、断流时换其他外部池。'),
      sel(`${EP}externalPoolStreamResponseMode`, '默认 SSE 转发', '', [['event_passthrough', 'SSE 事件级透传']], { advanced: true }),
    ],
  },
  {
    id: 'auto-disable',
    title: '自动禁用',
    fields: [
      bool(`${EP}externalPoolAutoDisableEnabled`, '启用自动禁用', '外部池出现明确的不可用错误时自动停用一段时间。'),
      bool(`${EP}externalPoolAutoDisableOnAuthError`, '认证错误', '', { disabledWhen: off(`${EP}externalPoolAutoDisableEnabled`) }),
      bool(`${EP}externalPoolAutoDisableOnSecurityLock`, '安全锁定', '', { disabledWhen: off(`${EP}externalPoolAutoDisableEnabled`) }),
      bool(`${EP}externalPoolAutoDisableOnQuotaExhausted`, '额度耗尽', '', { disabledWhen: off(`${EP}externalPoolAutoDisableEnabled`) }),
      bool(`${EP}externalPoolAutoDisableOnMisconfiguredEndpoint`, '端点配置错误', '', {
        disabledWhen: off(`${EP}externalPoolAutoDisableEnabled`),
      }),
      bool(`${EP}externalPoolAutoDisableOnChannelDisabled`, '上游通道禁用', '', {
        disabledWhen: off(`${EP}externalPoolAutoDisableEnabled`),
      }),
      num(`${EP}externalPoolAutoDisableFailureThreshold`, '触发阈值', '', {
        min: 1,
        suffix: '次',
        disabledWhen: off(`${EP}externalPoolAutoDisableEnabled`),
      }),
      num(`${EP}externalPoolAutoDisableWindowSecs`, '统计窗口', '', {
        min: 1,
        suffix: '秒',
        disabledWhen: off(`${EP}externalPoolAutoDisableEnabled`),
      }),
      num(`${EP}externalPoolAutoDisableDurationSecs`, '禁用时长', '0 表示直到手动解除。', {
        min: 0,
        suffix: '秒',
        disabledWhen: off(`${EP}externalPoolAutoDisableEnabled`),
      }),
    ],
  },
  {
    id: 'quality',
    title: '质量感知调度',
    fields: [
      bool(`${EP}externalPoolQualityAwareSchedulingEnabled`, '启用质量感知调度', '关闭后退回"优先级 → 负载"的排序，可作为快速回退手段。'),
      num(`${EP}externalPoolQualityTopK`, '候选池数量 K', '在评分最优的 K 个池里加权随机挑选。', {
        min: 1,
        max: 100,
        suffix: '个',
        disabledWhen: off(`${EP}externalPoolQualityAwareSchedulingEnabled`),
      }),
      num(`${EP}externalPoolDegradeErrorRateThreshold`, '降级失败率阈值', '失败率达到该比例即临时降级。', {
        min: 0,
        max: 1,
        step: 0.05,
        suffix: '比例',
        disabledWhen: off(`${EP}externalPoolQualityAwareSchedulingEnabled`),
      }),
      num(`${EP}externalPoolDegradeWindowSecs`, '劣化判定窗口', '', {
        min: 1,
        max: 86_400,
        suffix: '秒',
        disabledWhen: off(`${EP}externalPoolQualityAwareSchedulingEnabled`),
      }),
      num(`${EP}externalPoolDegradeProbationSecs`, '单次降级时长', '连续触发按 2 倍延长。', {
        min: 1,
        max: 86_400,
        suffix: '秒',
        disabledWhen: off(`${EP}externalPoolQualityAwareSchedulingEnabled`),
      }),
      num(`${EP}externalPoolMaxProbationSecs`, '最长降级时长', '不得低于单次降级时长。', {
        min: 1,
        max: 86_400,
        suffix: '秒',
        disabledWhen: off(`${EP}externalPoolQualityAwareSchedulingEnabled`),
      }),
      num(`${EP}externalPoolProbeSharePercent`, '降级期探测流量', '被降级池仍保留的流量比例；0 会变成硬避让。', {
        min: 0,
        max: 100,
        suffix: '%',
        disabledWhen: off(`${EP}externalPoolQualityAwareSchedulingEnabled`),
      }),
      num(`${EP}externalPoolRecoveryRampSecs`, '恢复爬坡时长', '降级到期后流量线性回升的时长。', {
        min: 0,
        max: 86_400,
        suffix: '秒',
        disabledWhen: off(`${EP}externalPoolQualityAwareSchedulingEnabled`),
      }),
      num(`${EP}externalPoolQualityErrorWeight`, '失败率权重', '', {
        min: 0,
        max: 1_000_000,
        step: 1,
        suffix: '权重',
        advanced: true,
        disabledWhen: off(`${EP}externalPoolQualityAwareSchedulingEnabled`),
      }),
      num(`${EP}externalPoolQualityLatencyWeight`, '延迟权重', '', {
        min: 0,
        max: 1_000_000,
        step: 1,
        suffix: '权重',
        advanced: true,
        disabledWhen: off(`${EP}externalPoolQualityAwareSchedulingEnabled`),
      }),
      num(`${EP}externalPoolQualityLoadWeight`, '负载权重', '', {
        min: 0,
        max: 1_000_000,
        step: 1,
        suffix: '权重',
        advanced: true,
        disabledWhen: off(`${EP}externalPoolQualityAwareSchedulingEnabled`),
      }),
      num(`${EP}externalPoolQualityProbationWeight`, '降级权重', '', {
        min: 0,
        max: 1_000_000,
        step: 1,
        suffix: '权重',
        advanced: true,
        disabledWhen: off(`${EP}externalPoolQualityAwareSchedulingEnabled`),
      }),
      num(`${EP}externalPoolQualityPriorityWeight`, '优先级权重', '仅用于展示分数构成。', {
        min: 0,
        max: 1_000_000,
        step: 1,
        suffix: '权重',
        advanced: true,
        disabledWhen: off(`${EP}externalPoolQualityAwareSchedulingEnabled`),
      }),
      num(`${EP}externalPoolQualityEwmaAlpha`, '质量平滑系数', '', {
        min: 0.01,
        max: 1,
        step: 0.01,
        suffix: '系数',
        advanced: true,
        disabledWhen: off(`${EP}externalPoolQualityAwareSchedulingEnabled`),
      }),
      num(`${EP}externalPoolQualityMinSamples`, '最少样本数', '', {
        min: 1,
        max: 10_000,
        suffix: '次',
        advanced: true,
        disabledWhen: off(`${EP}externalPoolQualityAwareSchedulingEnabled`),
      }),
      num(`${EP}externalPoolQualitySampleTtlSecs`, '质量数据有效期', '', {
        min: 1,
        max: 86_400,
        suffix: '秒',
        advanced: true,
        disabledWhen: off(`${EP}externalPoolQualityAwareSchedulingEnabled`),
      }),
    ],
  },
  {
    id: 'billing',
    title: '用量投影（按路径整理的外部池）',
    description: '只作用于"下游 usage 口径 = 按入口路径整理"的外部池',
    fields: [
      bool(`${EP}externalPoolUsageProjectionCostFloorEnabled`, '启用成本底线', '上报成本低于上游原始成本时补齐。'),
      num(`${EP}externalPoolUsageProjectionCostFloorMarginPercent`, '成本补齐余量', '', {
        min: 0,
        suffix: '%',
        disabledWhen: off(`${EP}externalPoolUsageProjectionCostFloorEnabled`),
      }),
      num(`${EP}externalPoolUsageProjectionUpliftPercent`, '缓存读写放大', '0 表示关闭。', { min: 0, suffix: '%' }),
      num(`${EP}externalPoolUsageProjectionOutputUpliftMinTokens`, '输出补偿阈值', '输出超过该值后开始放大；0 表示关闭。', {
        min: 0,
        suffix: 'tokens',
      }),
      num(`${EP}externalPoolUsageProjectionOutputUpliftPercent`, '输出放大', '', { min: 0, suffix: '%' }),
    ],
  },
  {
    id: 'debug',
    title: '诊断记录',
    fields: [
      bool(`${EP}externalPoolUsageDebugEnabled`, '记录 usage 原始数据', '临时记录外部池上游原始响应 usage 样本；默认关闭。'),
      { kind: 'text', path: `${EP}externalPoolUsageDebugDir`, label: '诊断目录', disabledWhen: off(`${EP}externalPoolUsageDebugEnabled`) },
      num(`${EP}externalPoolUsageDebugMaxBodyBytes`, '单条片段上限', '', {
        min: 0,
        max: 1024 * 1024,
        suffix: 'Bytes',
        disabledWhen: off(`${EP}externalPoolUsageDebugEnabled`),
      }),
      num(`${EP}externalPoolUsageDebugMaxFiles`, '最多诊断文件', '', {
        min: 0,
        max: 100_000,
        suffix: '个',
        disabledWhen: off(`${EP}externalPoolUsageDebugEnabled`),
      }),
    ],
  },
]
