import type { Config } from 'tailwindcss'
import daisyui from 'daisyui'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  safelist: [
    // Alerts
    'alert', 'alert-error', 'alert-info', 'alert-success', 'alert-warning',
    // Badges
    'badge', 'badge-accent', 'badge-error', 'badge-ghost', 'badge-info',
    'badge-neutral', 'badge-primary', 'badge-secondary', 'badge-sm', 'badge-xs',
    'badge-success', 'badge-warning',
    // Buttons
    'btn', 'btn-accent', 'btn-circle', 'btn-error', 'btn-ghost', 'btn-info',
    'btn-neutral', 'btn-outline', 'btn-primary', 'btn-secondary', 'btn-sm',
    'btn-square', 'btn-success', 'btn-warning', 'btn-xs',
    // Cards
    'card', 'card-bordered', 'card-body',
    // Forms
    'checkbox', 'checkbox-sm', 'checkbox-xs',
    'form-control', 'input', 'input-bordered', 'input-sm', 'input-xs',
    'select', 'select-bordered', 'select-sm', 'select-xs',
    'textarea', 'textarea-bordered', 'textarea-sm', 'textarea-xs',
    'toggle', 'toggle-primary', 'toggle-sm', 'toggle-success', 'toggle-xs',
    // Layout
    'collapse', 'collapse-arrow', 'collapse-content', 'collapse-title',
    'join', 'join-item',
    'modal', 'modal-action', 'modal-backdrop', 'modal-box',
    'navbar', 'navbar-end', 'navbar-start',
    // Feedback
    'loading', 'loading-lg', 'loading-sm', 'loading-spinner', 'loading-xs',
    'progress', 'progress-primary',
    // Data
    'stat', 'stat-desc', 'stat-title', 'stat-value', 'stats',
    'table', 'table-sm', 'table-zebra',
    // Labels
    'label', 'label-text', 'label-text-alt',
    // Menu
    'menu', 'dropdown', 'dropdown-content', 'dropdown-end',
    // Tooltip
    'tooltip', 'tooltip-right',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'Monaco', 'monospace'],
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-up': 'slideUp 0.2s ease-out',
        'slide-down': 'slideDown 0.2s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        // 浅色主题 - 蓝青渐变
        kiroLight: {
          primary: '#2563EB',
          'primary-content': '#FFFFFF',
          secondary: '#0D9488',
          'secondary-content': '#FFFFFF',
          accent: '#7C3AED',
          'accent-content': '#FFFFFF',
          neutral: '#1F2937',
          'neutral-content': '#F9FAFB',
          'base-100': '#FFFFFF',
          'base-200': '#F8FAFC',
          'base-300': '#E2E8F0',
          'base-content': '#1E293B',
          info: '#0EA5E9',
          'info-content': '#FFFFFF',
          success: '#10B981',
          'success-content': '#FFFFFF',
          warning: '#F59E0B',
          'warning-content': '#FFFFFF',
          error: '#EF4444',
          'error-content': '#FFFFFF',
          '--rounded-box': '0.75rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '0.5rem',
          '--animation-btn': '0.15s',
          '--btn-focus-scale': '0.98',
          '--border-btn': '1px',
          '--tab-border': '1px',
          '--tab-radius': '0.5rem',
        },
      },
      {
        // 深色主题 - 蓝青渐变
        kiroDark: {
          primary: '#60A5FA',
          'primary-content': '#0C1929',
          secondary: '#2DD4BF',
          'secondary-content': '#042F2E',
          accent: '#A78BFA',
          'accent-content': '#1E1B4B',
          neutral: '#E5E7EB',
          'neutral-content': '#111827',
          'base-100': '#0F172A',
          'base-200': '#1E293B',
          'base-300': '#334155',
          'base-content': '#F1F5F9',
          info: '#38BDF8',
          'info-content': '#082F49',
          success: '#34D399',
          'success-content': '#064E3B',
          warning: '#FBBF24',
          'warning-content': '#451A03',
          error: '#F87171',
          'error-content': '#450A0A',
          '--rounded-box': '0.75rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '0.5rem',
          '--animation-btn': '0.15s',
          '--btn-focus-scale': '0.98',
          '--border-btn': '1px',
          '--tab-border': '1px',
          '--tab-radius': '0.5rem',
        },
      },
      {
        // 海洋主题 - 深蓝色调
        kiroOcean: {
          primary: '#0284C7',
          'primary-content': '#FFFFFF',
          secondary: '#06B6D4',
          'secondary-content': '#FFFFFF',
          accent: '#8B5CF6',
          'accent-content': '#FFFFFF',
          neutral: '#164E63',
          'neutral-content': '#ECFEFF',
          'base-100': '#0C4A6E',
          'base-200': '#075985',
          'base-300': '#0369A1',
          'base-content': '#E0F2FE',
          info: '#22D3EE',
          'info-content': '#083344',
          success: '#4ADE80',
          'success-content': '#052E16',
          warning: '#FCD34D',
          'warning-content': '#451A03',
          error: '#FB7185',
          'error-content': '#4C0519',
          '--rounded-box': '0.75rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '0.5rem',
          '--animation-btn': '0.15s',
          '--btn-focus-scale': '0.98',
          '--border-btn': '1px',
          '--tab-border': '1px',
          '--tab-radius': '0.5rem',
        },
      },
      {
        // 森林主题 - 绿色调
        kiroForest: {
          primary: '#059669',
          'primary-content': '#FFFFFF',
          secondary: '#84CC16',
          'secondary-content': '#1A2E05',
          accent: '#14B8A6',
          'accent-content': '#FFFFFF',
          neutral: '#1C4532',
          'neutral-content': '#ECFDF5',
          'base-100': '#064E3B',
          'base-200': '#065F46',
          'base-300': '#047857',
          'base-content': '#D1FAE5',
          info: '#67E8F9',
          'info-content': '#083344',
          success: '#A3E635',
          'success-content': '#1A2E05',
          warning: '#FDE047',
          'warning-content': '#422006',
          error: '#FCA5A5',
          'error-content': '#450A0A',
          '--rounded-box': '0.75rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '0.5rem',
          '--animation-btn': '0.15s',
          '--btn-focus-scale': '0.98',
          '--border-btn': '1px',
          '--tab-border': '1px',
          '--tab-radius': '0.5rem',
        },
      },
      {
        // 紫罗兰主题 - 紫色调
        kiroPurple: {
          primary: '#8B5CF6',
          'primary-content': '#FFFFFF',
          secondary: '#EC4899',
          'secondary-content': '#FFFFFF',
          accent: '#06B6D4',
          'accent-content': '#FFFFFF',
          neutral: '#3B0764',
          'neutral-content': '#FAF5FF',
          'base-100': '#2E1065',
          'base-200': '#3B0764',
          'base-300': '#581C87',
          'base-content': '#F3E8FF',
          info: '#38BDF8',
          'info-content': '#082F49',
          success: '#4ADE80',
          'success-content': '#052E16',
          warning: '#FBBF24',
          'warning-content': '#451A03',
          error: '#FB7185',
          'error-content': '#4C0519',
          '--rounded-box': '0.75rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '0.5rem',
          '--animation-btn': '0.15s',
          '--btn-focus-scale': '0.98',
          '--border-btn': '1px',
          '--tab-border': '1px',
          '--tab-radius': '0.5rem',
        },
      },
      {
        // 日落主题 - 橙红色调
        kiroSunset: {
          primary: '#F97316',
          'primary-content': '#FFFFFF',
          secondary: '#F43F5E',
          'secondary-content': '#FFFFFF',
          accent: '#FBBF24',
          'accent-content': '#451A03',
          neutral: '#7C2D12',
          'neutral-content': '#FFF7ED',
          'base-100': '#431407',
          'base-200': '#7C2D12',
          'base-300': '#9A3412',
          'base-content': '#FFEDD5',
          info: '#38BDF8',
          'info-content': '#082F49',
          success: '#4ADE80',
          'success-content': '#052E16',
          warning: '#FDE047',
          'warning-content': '#422006',
          error: '#FCA5A5',
          'error-content': '#450A0A',
          '--rounded-box': '0.75rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '0.5rem',
          '--animation-btn': '0.15s',
          '--btn-focus-scale': '0.98',
          '--border-btn': '1px',
          '--tab-border': '1px',
          '--tab-radius': '0.5rem',
        },
      },
    ],
  },
} satisfies Config
