import type { Config } from 'tailwindcss'
import daisyui from 'daisyui'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  safelist: [
    'alert',
    'alert-error',
    'alert-info',
    'alert-success',
    'alert-warning',
    'badge',
    'badge-accent',
    'badge-error',
    'badge-ghost',
    'badge-info',
    'badge-neutral',
    'badge-primary',
    'badge-secondary',
    'badge-sm',
    'badge-success',
    'badge-warning',
    'btn',
    'btn-accent',
    'btn-circle',
    'btn-error',
    'btn-ghost',
    'btn-info',
    'btn-neutral',
    'btn-outline',
    'btn-primary',
    'btn-secondary',
    'btn-sm',
    'btn-square',
    'btn-success',
    'btn-warning',
    'btn-xs',
    'card',
    'card-bordered',
    'card-body',
    'checkbox',
    'checkbox-sm',
    'collapse',
    'collapse-arrow',
    'collapse-content',
    'collapse-title',
    'form-control',
    'input',
    'input-bordered',
    'input-xs',
    'join',
    'join-item',
    'label',
    'label-text',
    'label-text-alt',
    'loading',
    'loading-lg',
    'loading-sm',
    'loading-spinner',
    'loading-xs',
    'menu',
    'modal',
    'modal-action',
    'modal-backdrop',
    'modal-box',
    'navbar',
    'navbar-end',
    'navbar-start',
    'progress',
    'progress-primary',
    'select',
    'select-bordered',
    'stat',
    'stat-desc',
    'stat-title',
    'stat-value',
    'stats',
    'table',
    'table-sm',
    'table-zebra',
    'textarea',
    'textarea-bordered',
    'toggle',
    'toggle-primary',
    'toggle-success',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [daisyui],
  daisyui: {
    themes: [
      {
        kiroLight: {
          primary: '#2563EB',
          'primary-content': '#FFFFFF',
          secondary: '#0F766E',
          'secondary-content': '#FFFFFF',
          accent: '#7C3AED',
          'accent-content': '#FFFFFF',
          neutral: '#111827',
          'neutral-content': '#F8FAFC',
          'base-100': '#FFFFFF',
          'base-200': '#F5F7FA',
          'base-300': '#D7DEE8',
          'base-content': '#111827',
          info: '#0369A1',
          'info-content': '#FFFFFF',
          success: '#15803D',
          'success-content': '#FFFFFF',
          warning: '#B45309',
          'warning-content': '#FFFFFF',
          error: '#DC2626',
          'error-content': '#FFFFFF',
          '--rounded-box': '0.5rem',
          '--rounded-btn': '0.375rem',
          '--rounded-badge': '0.375rem',
          '--animation-btn': '0.15s',
          '--btn-focus-scale': '0.99',
          '--border-btn': '1px',
          '--tab-border': '1px',
          '--tab-radius': '0.375rem',
        },
      },
      {
        kiroDark: {
          primary: '#60A5FA',
          'primary-content': '#061225',
          secondary: '#2DD4BF',
          'secondary-content': '#041512',
          accent: '#A78BFA',
          'accent-content': '#120A2A',
          neutral: '#E5E7EB',
          'neutral-content': '#0B1120',
          'base-100': '#111827',
          'base-200': '#0B1120',
          'base-300': '#263244',
          'base-content': '#E5E7EB',
          info: '#7DD3FC',
          'info-content': '#082F49',
          success: '#4ADE80',
          'success-content': '#052E16',
          warning: '#FBBF24',
          'warning-content': '#451A03',
          error: '#F87171',
          'error-content': '#450A0A',
          '--rounded-box': '0.5rem',
          '--rounded-btn': '0.375rem',
          '--rounded-badge': '0.375rem',
          '--animation-btn': '0.15s',
          '--btn-focus-scale': '0.99',
          '--border-btn': '1px',
          '--tab-border': '1px',
          '--tab-radius': '0.375rem',
        },
      },
    ],
  },
} satisfies Config
